# Generated by Django 5.1.6 on 2025-04-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_alter_meeting_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='link',
            field=models.URLField(help_text='recommand using Google meet'),
        ),
    ]
