# Generated by Django 5.1.6 on 2025-03-05 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SessionAcademique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('academic_level', models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('Master 1', 'Master 1'), ('Master 2', 'Master 2')], default='1st Year', max_length=50)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SessionAcademique.academicsession')),
            ],
        ),
    ]
