# Generated by Django 5.1.6 on 2025-02-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='academic_level',
            field=models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year'), ('Master 1', 'Master 1'), ('Master 2', 'Master 2')], default='1st Year', max_length=50),
        ),
    ]
