# Generated by Django 5.1.6 on 2025-02-26 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('projetTask', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='projects/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetTask.projectsubmissiontask')),
            ],
        ),
    ]
