# Generated by Django 5.1.6 on 2025-02-17 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_emailverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
