# Generated by Django 5.1.6 on 2025-02-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_delete_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_professor',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
