# Generated by Django 5.1.6 on 2025-02-26 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('groupe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubmissionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.professor')),
                ('groups', models.ManyToManyField(to='groupe.group')),
            ],
        ),
    ]
