# Generated by Django 5.1.6 on 2025-03-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetTask', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubmissiontask',
            name='coef',
            field=models.IntegerField(default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='projectsubmissiontask',
            name='description',
            field=models.TextField(),
        ),
    ]
