# Generated by Django 5.1.6 on 2025-03-06 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetTask', '0002_projectsubmissiontask_coef_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsubmissiontask',
            name='coef',
        ),
    ]
